//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ShaBoo.Entities
{
    public partial class Document
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public string Intro { get; set; }
        public string Suffix { get; set; }
        public int Size { get; set; }
        public short Views { get; set; }
        public short Downloads { get; set; }
        public System.DateTime UploadedOn { get; set; }
        public int FstClassID { get; set; }
        public int SndClassID { get; set; }
        public int TrdClassID { get; set; }
        public int ProfileID { get; set; }
    
        public virtual FstClass FstClass { get; set; }
        public virtual SndClass SndClass { get; set; }
        public virtual TrdClass TrdClass { get; set; }
        public virtual Profile Profile { get; set; }
    }
    
}
