//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ShaBoo.Entities
{
    public partial class FstClass
    {
        public FstClass()
        {
            this.SndClass = new HashSet<SndClass>();
            this.Document = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SndClass> SndClass { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
    
}
