//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ShaBoo.Entities
{
    public partial class Profile
    {
        public Profile()
        {
            this.Document = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Alias { get; set; }
        public string Email { get; set; }
        public string Intro { get; set; }
        public int Point { get; set; }
        public string UID { get; set; }
    
        public virtual ICollection<Document> Document { get; set; }
    }
    
}
