//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ShaBoo.Entities
{
    public partial class ShaBooContainer : DbContext
    {
        public ShaBooContainer()
            : base("name=ShaBooContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Role> RoleSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Document> DocumentSet { get; set; }
        public DbSet<Profile> ProfileSet { get; set; }
        public DbSet<FstClass> FstClassSet { get; set; }
        public DbSet<SndClass> SndClassSet { get; set; }
        public DbSet<TrdClass> TrdClassSet { get; set; }
        public DbSet<Board> BoardSet { get; set; }
    }
}
